rules:
# Currently we allow a small subset of valid types of PRs to get merged.  The following three
# rules can be used altogether or any subset. The bot confirms that incoming pull requests'
# author match the authors below, and subsequently, the allowed title of the pull requests.
# `changedFiles` are allowed patterns for the file paths that are changed in a PR, and 
# `maxFiles` are the maximum amount of files that are allowed to be changed in that PR. Neither
# changedFiles nor maxFiles are required, but they will be enforced on a PR if they are set.
# Each rule only has the allowed values listed below; there is no mixing of values between rules,
# nor can any values be replaced. To understand the full set of rules for the JSON file, check out
# src/valid-pr-schema.json

- author: "imgbot"
  title: "^[ImgBot] Optimize images$"
