# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  
  workflow_run:
    workflows: [README]
    types:
      - completed
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Skills Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: skills-metrics.svg
          output_action: commit
          committer_message: "chore: update skills metrics"
          
          # Options
          user: aksalsf
          template: classic
          base: ""
          config_display: large
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_topics_sort: random

      - name: Habits Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: habits-metrics.svg
          output_action: commit
          committer_message: "chore: update habits metrics"
          
          # Options
          user: aksalsf
          template: classic
          base: ""
          config_display: large
          config_timezone: Asia/Jakarta
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 16
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes

      - name: Social Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: social-metrics.svg
          output_action: commit
          committer_message: "chore: update social metrics"
          
          # Options
          user: aksalsf
          template: classic
          base: ""
          config_display: large
          config_timezone: Asia/Jakarta
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_discussions_categories_limit: 4
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 3
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-recent, answers-top, questions-recent, questions-top
          plugin_stackoverflow_user: 17299094

      - name: Achievement Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: achievement-metrics.svg
          output_action: commit
          committer_message: "chore: update achievement metrics"
          
          # Options
          user: aksalsf
          template: classic
          base: ""
          config_display: large
          config_timezone: Asia/Jakarta
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
