# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  
  workflow_run:
    workflows: [Build README.md]
    types:
      - completed
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Left Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: left-metrics.svg
          output_action: commit
          committer_message: "chore: update left metrics"

          # Options
          user: aksalsf
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 24
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_activity: yes
          plugin_activity_days: 7
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: mastered
          plugin_topics_sort: stars

      - name: Right Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: right-metrics.svg
          output_action: commit
          committer_message: "chore: update right metrics"
          
          # Options
          user: aksalsf
          template: classic
          base: ""
          config_timezone: Asia/Jakarta
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_discussions_categories_limit: 4
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_types: commit
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 3
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_stackoverflow_user: 17299094
      
      - name: Achievement Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: achievement-metrics.svg
          output_action: commit
          committer_message: "chore: update achievement metrics"
          
          # Options
          user: aksalsf
          template: classic
          base: ""
          config_timezone: Asia/Jakarta
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
      
      - name: People Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: people-metrics.svg
          output_action: commit
          committer_message: "chore: update people metrics"
          
          # Options
          user: aksalsf
          template: classic
          base: ""
          config_timezone: Asia/Jakarta
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_fortune: yes
